### ISSUE TITLE
Support Carta v4

### ISSUE THREAD

**Issue by maisonsmd** [maisonsmd/carta-plugin-subscript#1]
Carta has [breaking changes](https://beartocode.github.io/carta/migration) so that this plugin cannot work with in v4.

Need to revise and migrate to support Carta v4.

**Comment by jstjoe** [comment]
Please! :D

**Comment by maisonsmd** [comment]
@jstjoe 

Yeah I'm updating all of my plugins, this should be available in 1 day or 2.
